# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5fYXtAunzL68vh-CqSHEbsjzQfMwmsx
"""

import requests
import json
import os
from datetime import datetime, timedelta

# --- CONFIGURATION ---
API_KEY = os.environ.get("SAM_API_KEY")
BASE_URL = "https://api.sam.gov/opportunities/v2/search"
NAICS = "238290"    # Elevator/Conveyance
REGION = "HI"       # Hawaii Only
PTYPES = ["o", "k"] # Solicitations, Combined Synopsis

def pull_sam_data(ptype):
    """Fetches data for a specific opportunity type."""
    params = {
        "limit": "100",
        "postedFrom": (datetime.now() - timedelta(days=60)).strftime('%m/%d/%Y'),
        "postedTo": datetime.now().strftime('%m/%d/%Y'),
        "ncode": NAICS,
        "state": REGION,
        "ptype": ptype,
        "api_key": API_KEY
    }

    try:
        r = requests.get(BASE_URL, params=params, timeout=60)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        print(f"Warning: ptype '{ptype}' fetch failed: {e}")
        return {}

def main():
    print(f"Fetching SAM.gov opportunities for NAICS {NAICS} in {REGION}...")

    all_raw_data = []
    for p in PTYPES:
        all_raw_data.append(pull_sam_data(p))

    opportunities = []
    seen_ids = set()

    for data in all_raw_data:
        # Guard against empty/malformed responses
        ops_list = data.get("opportunitiesData", [])
        if not ops_list:
            continue

        for op in ops_list:
            # unique key generation
            key = op.get("solicitationNumber") or op.get("noticeId") or op.get("title")
            if not key or key in seen_ids:
                continue
            seen_ids.add(key)

            # Robust field extraction
            opportunities.append({
                "title": op.get("title", "Untitled Opportunity"),
                "solicitationNumber": op.get("solicitationNumber", "N/A"),
                "agency": op.get("department") or op.get("office") or "Unknown Agency",
                "postedDate": op.get("postedDate"),
                "responseDeadline": op.get("responseDeadLine") or op.get("archiveDate"),
                "link": op.get("uiLink") or "#",
                "description": op.get("description", ""),
                "setAside": op.get("typeOfSetAsideDescription", "").strip()
            })

    # Save to JSON
    with open('opportunities.json', 'w') as f:
        json.dump(opportunities, f)

    print(f"✅ Success: Saved {len(opportunities)} unique opportunities.")

if __name__ == "__main__":
    main()